application: ghicalls
version: 2
runtime: python27
api_version: 1
threadsafe: no

handlers:
- url: /(.*\.(mp3|wav))
  static_files: \1
  upload: (.*\.(mp3|wav))
- url: /.*
  script: ghicalls.py
